# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10ca662b91bc185a74c0aa84228f4d989afa14b7aa4d87bc9a54dbbc6fa8262d22efb79f570430e3c09d2ff88392a629839134171778f18eb7d93cf866b533fc

test:
  secret_key_base: 3e98bf6c88db5ed970e5299cfc82a86d315568b8aca76168c82c7e4d2b7f1078a9056b39f8134a5f291f4c71002bbdc31d9afd08cacaad57f619979677e31afe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
